sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Z8XLRe2cj2neHp4R5OuNe6MAX5phU+AWg3aWKg8reiym8Nj3dYi39+fTEv88MyepOAl+OqR8pgRt70dGScsdrB5d13PBB52zgnA93OEGn1lb4tnepbyGY29cMPC5a/7U7FmR1v85upUHbBdtClnW17iqSPEAW6WBvtV6JdZuJgXITtsMpA2Fm5OI1LK523xQDC2aDdmlVWvRr1gRI8Drj+nZUNvfuMrBuhtk3VdZLWOK7fPpyn5x8Xr8WG3wnKKkbOY8YM2mtNScBY3wuKRXObfo7TJRzbbbKbLEzIMzVwYI2DFiXDK9KUlbS5ddH7L5MOHt/ifS8t+lmWA981K2bXQsgUHy6J/x5mwzrUvt5l9frbN9kumLIU1vZM/KuNT2zf90/+eR9FviPNIwx8mjIWP80xfdrzBszURNymIhGMz8YsuaHfhFB1wEWJs0okkza0ADXND9CS46rBnLQ+kb1muFpdJicajvKH4XWEATs626JobgxAi+kapvsupTbUaLUQKqYbVApYnVIjZv6oQzY3ab5XXv12IIsxiT4dNUWTPPg3+5RMWLlc7SuHgchu+EO0HP1TGSk4HRyMcbWhBQGSVErWWmWeW5NVegoM09ITkdC/Ga75ax/Q5URYJuIVCLS9PJUv/ZXvjuRcTK5QA+OIla1stobFIcH4PyYi+/xEY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Arabian-Nights-Entertainments_128
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy